--- #YAML:1.0
name:               Catalyst-Plugin-Session-Store-Jifty-DBI
version:            0.02
abstract:           Store your session with Jifty::DBI
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Model::Jifty::DBI:  0.06
    Catalyst::Plugin::Session:  0.15
    Catalyst::Runtime:    5.70
    DBD::SQLite:          1.25
    MIME::Base64:         0
    Storable:             0
    Test::More:           0.47
    Test::UseAllModules:  0.09
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
